return {
  goimports = {},
  gofumpt = {},
  goimports_reviser = {},
  golines = {},
  yamlfmt = {},
  -- eslint_d = {},
  -- fixjson = {},
  mdformat = {},
  prettier = {},
  prettierd = {},
  -- terrafmt = {},
  rustywind = {},
  sqlfmt = {},
  -- ruff = {},
  -- mypy = {},
  black = {},
}
